name: consumers_backend
description: Consumers backend serving Consumers REST API.
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  arango_driver: ^3.6.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  consumers_api:
    path: ../consumers_api

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
